version: '3'
services:
  caddy:
    image: caddy:latest
    ports:
      - 4443:443
    volumes:
      - ./caddy:/etc/caddy
      - caddy_config:/config

  httpbin:
    image: kennethreitz/httpbin:latest
    ports:
      - 8888:80

volumes:
  caddy_data:
  caddy_config:
